
# docker/docker-compose.yml
version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: erp
      POSTGRES_PASSWORD: erp
      POSTGRES_DB: erpdb
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
